/* global window, document */
(function () {
  'use strict';
  const esc = v => String(v || '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' })[c]);
  const allowed = () => (window.RIP_FIREBASE_ALLOWED_EMAILS || []).map(v => String(v).toLowerCase());
  async function env() { return window.RIPFirebase.ready; }
  async function isManager() { const e = await env(); return allowed().includes(String(e.user?.email || '').toLowerCase()); }
  function teachers() { return Array.from(new Set((window.RIPApp?.state?.registro || []).map(r => String(r?.profesor || '').trim()).filter(Boolean))).sort((a,b) => a.localeCompare(b, 'es')); }
  async function getProfiles() { const e = await env(); const s = await e.fs.getDocs(e.fs.collection(e.db, 'users')); return s.docs.map(d => ({ id:d.id, ...d.data() })); }
  async function open() {
    if (!(await isManager())) return window.alert('Debes ingresar con una cuenta administradora para gestionar vínculos.');
    document.getElementById('ripAccessModal')?.remove();
    const modal = document.createElement('div'); modal.id = 'ripAccessModal'; modal.style.cssText = 'position:fixed;inset:0;z-index:100001;background:rgba(15,23,42,.5);display:grid;place-items:center;padding:18px;font-family:system-ui,sans-serif';
    modal.innerHTML = `<section style="background:#fff;width:min(820px,100%);max-height:88vh;overflow:auto;border-radius:14px;padding:22px"><button data-close style="float:right;border:0;background:none;font-size:24px;cursor:pointer">×</button><h2 style="margin:0;color:#1A3B6E">Vinculación de docentes</h2><p style="color:#64748b">Selecciona el docente que aparece en RIP y conéctalo con su correo Google.</p><form data-form style="display:grid;grid-template-columns:1fr 1fr;gap:12px;background:#f6f8fb;padding:14px;border-radius:10px"><label>Docente RIP<select name="teacher" required style="display:block;width:100%;padding:9px;margin-top:5px"><option value="">Selecciona…</option>${teachers().map(t => `<option value="${esc(t)}">${esc(t)}</option>`).join('')}</select></label><label>Correo Google<input name="email" type="email" required style="display:block;width:100%;box-sizing:border-box;padding:9px;margin-top:5px"></label><label>Nombre<input name="name" style="display:block;width:100%;box-sizing:border-box;padding:9px;margin-top:5px"></label><label>Rol<select name="role" style="display:block;width:100%;padding:9px;margin-top:5px"><option value="docente">Docente</option><option value="admin">Administrador</option></select></label><label style="grid-column:1/-1"><input name="active" type="checkbox" checked> Acceso activo</label><button style="grid-column:1/-1;padding:10px;border:0;border-radius:7px;background:#1A3B6E;color:white;font-weight:700;cursor:pointer">Guardar vínculo</button></form><h3>Vínculos actuales</h3><div data-list>Cargando…</div></section>`;
    document.body.appendChild(modal); modal.querySelector('[data-close]').onclick = () => modal.remove(); const list = modal.querySelector('[data-list]');
    const render = async () => { const rows = (await getProfiles()).sort((a,b) => String(a.teacherName || a.email).localeCompare(String(b.teacherName || b.email), 'es')); list.innerHTML = rows.length ? `<table style="width:100%;border-collapse:collapse"><tr><th align="left">Docente</th><th align="left">Correo</th><th align="left">Rol</th><th align="left">Estado</th></tr>${rows.map(p => `<tr><td style="padding:8px 0;border-top:1px solid #e5e7eb">${esc(p.teacherName || p.displayName)}</td><td style="border-top:1px solid #e5e7eb">${esc(p.email || p.id)}</td><td style="border-top:1px solid #e5e7eb">${esc(p.role)}</td><td style="border-top:1px solid #e5e7eb">${p.active === false ? 'Inactivo' : 'Activo'}</td></tr>`).join('')}</table>` : 'Sin vínculos todavía.'; };
    await render(); modal.querySelector('[data-form]').onsubmit = async event => { event.preventDefault(); const f = event.currentTarget; const e = await env(); const email = String(f.email.value || '').trim().toLowerCase(); await e.fs.setDoc(e.fs.doc(e.db, 'users', email), { email, teacherName:f.teacher.value, displayName:f.name.value, role:f.role.value, active:f.active.checked, updatedAt:e.fs.serverTimestamp(), updatedBy:e.user?.email || '' }, { merge:true }); f.reset(); f.active.checked = true; await render(); };
  }
  document.getElementById('btnAccessSettings')?.addEventListener('click', open);
})();
